---
experiment:
  name: deca/mit
dataset:
  data_dir: mit-states
  dataset: mitstates
  splitname: compositional-split-natural
model_params:
  model: deca
  dropout: true
  norm: true
  nlayers: 2
  relu: false
  fc_emb: 768,1024
  emb_dim: 600
  emb_init: ft+w2v
  image_extractor: resnet18
  train_only: true
  static_inp: false
training:
  seed: 2021
  cudnn_benchmark: false
  cudnn_deterministic: true
  batch_size: 256
  load:
  lr: 5.0e-04
  lrg: 5.0e-06
  cosine_scale: 20
  max_epochs: 150
  norm_family: imagenet
  save_every: 10000
  test_batch_size: 128
  test_set: val
  topk: 1
  wd: 5.0e-05
  workers: 8
  update_features: false
  freeze_features: false
  eval_val_every: 1
  similarity: cos
  alpha: 0.2
